[build]
  command = "npm install"
  functions = "functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true

[[redirects]]
  from = "/streams*"
  to = "/.netlify/functions/api"
  status = 200
  force = true
