[build]
  command = "npm install"
  functions = "functions"
  publish = "."

[functions]
  node_bundler = "esbuild"
  included_files = ["blocked.html", "Catalogue RP/**"]

[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/blocked"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/streams"
  to = "/.netlify/functions/api"
  status = 200
