[build]
  publish = "."
  functions = "functions"

# Redirections pour la connexion Discord
[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/api/auth/:splat"
  status = 200

# Redirections pour l'API des archives
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/api/:splat"
  status = 200
